server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingservice

  jpa:
    hibernate:
      ddl-auto: update

eureka:
      client:
        service-url:
          defaultZone: http://localhost:8084/eureka/

